package org.shareat.app.theme

import androidx.compose.ui.graphics.Color

internal val primaryLight = Color(0xFF8F4C36)
internal val onPrimaryLight = Color(0xFFFFFFFF)
internal val primaryContainerLight = Color(0xFFFFDBD0)
internal val onPrimaryContainerLight = Color(0xFF723521)
internal val secondaryLight = Color(0xFF006874)
internal val onSecondaryLight = Color(0xFFFFFFFF)
internal val secondaryContainerLight = Color(0xFF9EEFFD)
internal val onSecondaryContainerLight = Color(0xFF004F58)
internal val tertiaryLight = Color(0xFF4A672D)
internal val onTertiaryLight = Color(0xFFFFFFFF)
internal val tertiaryContainerLight = Color(0xFFCBEEA5)
internal val onTertiaryContainerLight = Color(0xFF334E17)
internal val errorLight = Color(0xFFBA1A1A)
internal val onErrorLight = Color(0xFFFFFFFF)
internal val errorContainerLight = Color(0xFFFFDAD6)
internal val onErrorContainerLight = Color(0xFF93000A)
internal val backgroundLight = Color(0xFFFFF8F6)
internal val onBackgroundLight = Color(0xFF231917)
internal val surfaceLight = Color(0xFFF5FAFB)
internal val onSurfaceLight = Color(0xFF171D1E)
internal val surfaceVariantLight = Color(0xFFF5DED7)
internal val onSurfaceVariantLight = Color(0xFF53433F)
internal val outlineLight = Color(0xFF85736E)
internal val outlineVariantLight = Color(0xFFD8C2BC)
internal val scrimLight = Color(0xFF000000)
internal val inverseSurfaceLight = Color(0xFF2B3133)
internal val inverseOnSurfaceLight = Color(0xFFECF2F3)
internal val inversePrimaryLight = Color(0xFFFFB59E)
internal val surfaceDimLight = Color(0xFFD5DBDC)
internal val surfaceBrightLight = Color(0xFFF5FAFB)
internal val surfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val surfaceContainerLowLight = Color(0xFFEFF5F6)
internal val surfaceContainerLight = Color(0xFFE9EFF0)
internal val surfaceContainerHighLight = Color(0xFFE3E9EA)
internal val surfaceContainerHighestLight = Color(0xFFDEE3E5)
